// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by Extensibility Tools v1.10.188
// </auto-generated>
// ------------------------------------------------------------------------------
namespace CssAutoPrefixer
{
    static class Vsix
    {
        public const string Id = "7df8a985-0e26-4aab-95fc-f48ee61b086a";
        public const string Name = "CSS AutoPrefixer";
        public const string Description = @"Write your CSS rules without vendor prefixes (in fact, forget about them entirely). Autoprefixer will use the data based on current browser popularity and property support to apply prefixes for you.";
        public const string Language = "en-US";
        public const string Version = "0.7";
        public const string Author = "Mads Kristensen";
        public const string Tags = "CSS, LESS, Sass, Scss, autoprefixer";
    }
}
