// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by Extensibility Tools v1.10.188
// </auto-generated>
// ------------------------------------------------------------------------------
namespace CssAutoPrefixer
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string guidPackageString = "1fb559a7-7c51-4b78-b941-697bd7764ade";
        public const string guidPackageCmdSetString = "df207aa8-51d1-44f8-b6c1-31af17cce355";
        public const string CssEditorString = "a5401142-f49d-43db-90b1-f57ba349e55c";
        public const string CssEditorWithEncodingString = "226f7e34-0ae8-4157-9cd8-b66b4eaf2c7b";
        public const string CssCmdSetString = "64da400e-b4ad-4d67-aa92-4b7acb01ecd5";
        public static Guid guidPackage = new Guid(guidPackageString);
        public static Guid guidPackageCmdSet = new Guid(guidPackageCmdSetString);
        public static Guid CssEditor = new Guid(CssEditorString);
        public static Guid CssEditorWithEncoding = new Guid(CssEditorWithEncodingString);
        public static Guid CssCmdSet = new Guid(CssCmdSetString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int MyMenuGroup = 0x1020;
        public const int AutoPrefixCommandId = 0x0100;
        public const int cssContextMenu = 0x0002;
    }
}
